### ISSUE TITLE
No project.json

### ISSUE THREAD

**Issue by tommysella** [rahulsahay19/generator-aspnetcore-angular-2#1]
Hi!

Why are you using .csproj and not project.json? It would be good if the templete you have created could be the same as the template included in Visual Studio for ASP.NET Core... ;-)

Best Regards,
Tommy

**Comment by rahulsahay19** [comment]
That's a good question. Entire motivation behind the same was giving LTS(Long Term Support) which basically says, that MS will get rid off project.json and .xproj type in coming releases just to embrace the existing ecosystem of .csproj type. This is why scaffolded templates like this. You can also refer my blog around the same. [Read it here!](http://myview.rahulnivi.net/goodbye-project-json-xproj-csproj/ )
